"""fw-context configuration loader.

Hierarchy (later overrides earlier):
  1. built-in defaults
  2. ~/.fw-context/config.toml           (global, per-user)
  3. <project>/.fw-context/config.toml   (project, shared — commit to git)
  4. <project>/.fw-context/local.toml    (project, local — gitignore)
"""

from __future__ import annotations

import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from ..indexer.build import BuildConfig

__all__ = [
    "CacheServerConfig",
    "Config",
    "LLMConfig",
    "IndexConfig",
    "ProjectMeta",
    "ProjectNotInitializedError",
    "derive_project_id",
    "generate_project_id",
    "load",
    "update_global_config",
]


class ProjectNotInitializedError(RuntimeError):
    """Raised when a project has not been initialized with ``fw-context init``."""

    def __init__(self, root: Path) -> None:
        self.root = root
        super().__init__(
            f"Project at {root} is not initialized.\n"
            "Run 'fw-context init' in the project root to generate a project ID."
        )


_GLOBAL_CONFIG_PATH = Path.home() / ".fw-context" / "config.toml"
_PROJECT_CONFIG_DIR = ".fw-context"
_PROJECT_CONFIG_NAME = "config.toml"
_PROJECT_LOCAL_CONFIG_NAME = "local.toml"

_GLOBAL_DEFAULTS = """\
[index]
db_dir = "~/.fw-context/index"

[llm]
# enabled = false   # uncomment to disable Ollama — LLM-calling tools will return raw prompts
ollama_url = "http://localhost:11434"

# Chat model for symbolic analysis and search query generation.
# Minimum recommended: 14B parameters — smaller models produce inconsistent JSON
# and poor-quality descriptions for C++ embedded code.
#
# Recommended models (min. 14B parameters):
#   Local:
#     qwen2.5-coder:14b        (4.8 GB VRAM, balanced speed/quality)
#     deepseek-coder-v2:16b    (10 GB VRAM, strong code comprehension)
#     qwen2.5-coder:32b        (19 GB VRAM, best local quality)
#   Cloud (Ollama proxies to cloud APIs — "ollama pull <model>"):
#     qwen3-coder:480b-cloud         (coding-focused, best quality)
#     deepseek-v4-flash:cloud        (284B MoE, 13B active — great value)
#     gemini-3-flash-preview:latest-cloud   (fast, affordable)
#   See: https://ollama.com/search?c=cloud
model = "qwen2.5-coder:14b"
num_ctx = 16384
# keep_alive = "10m"   # how long to keep model loaded in VRAM after each request
# timeout = 600.0   # HTTP timeout for Ollama requests in seconds (default 600)
# debug_log = "~/.fw-context/llm-debug.jsonl"   # write LLM prompts/responses to JSONL

# Embedding model for semantic_search.
# Pull with:  ollama pull <model>
# Uncomment exactly ONE of the sections below.
#
# ── Default: mxbai-embed-large (~670 MB VRAM, no GPU needed) ──
# embed_model = "mxbai-embed-large:latest"
# embed_query_prompt = "Represent this sentence for searching relevant passages: "
# embed_doc_prompt = ""
#
# ── Higher quality: qwen3-embedding:8b (~4.7 GB VRAM, GPU recommended) ──
# embed_model = "qwen3-embedding:8b"
# embed_query_prompt = "Retrieve C/C++ functions, types, symbols, and implementation code relevant to the query."
# embed_doc_prompt = ""

analyze_symbols = true
"""

_PROJECT_DEFAULTS_TEMPLATE = """\
[project]
# name = "my-project"   # defaults to directory name
# id = ""               # auto-generated by 'fw-context init' — do not edit

[build]
# Build system auto-detection: scans for .mbed, west.yml, or platformio.ini.
# Set system explicitly when auto-detection fails or you need to force a specific one.
# system = "mbed-os"        # choices: mbed-os, zephyr, platformio
# clean = true              # always clean build before indexing (recommended)
# command = "bear -- make"  # full override — bypasses all detection

# ── Mbed OS ──────────────────────────────────────────────────────────────
# Most values are auto-detected from .mbed and custom_targets.json.
# Override them here when auto-detection is wrong or incomplete.
#
# target = "P_ECB_BOARD"
# toolchain = "GCC_ARM"
# profile = "develop"
# app_config = "mbed_app.json"
# extra_profiles = ["lto.json"]
# defines = ["VERSION_FW_MAJOR=4", "DEV"]  # extra -D macros passed to compiler

# ── Zephyr ───────────────────────────────────────────────────────────────
# board is REQUIRED — there is no safe auto-detection for Zephyr boards.
# Set system = "zephyr" if west.yml coexists with another build system marker.
#
# system = "zephyr"
# board = "nrf52840dk_nrf52840"

# ── PlatformIO ───────────────────────────────────────────────────────────
# Usually needs no extra config — pio run --target compiledb is enough.
# system = "platformio"

[index]
compile_commands = "compile_commands.json"
# Generate it with:  fw-context index --build  (auto-detects build system)
# config_header = "config/my_build_config.h"   # path to config.h for custom build systems
#vendor_paths = ["third_party", "vendor_libs"]
#project_paths = ["src/old_hal", "lib/muj_modul"]
#  Pro cesty MIMO project_root používejte ABSOLUTNÍ cesty:
#  project_paths = ["/home/user/esp/components/muj_fork"]

# index_refs: build a cross-reference / call graph.
#   On by default — enables find_callers, find_call_path, find_dead_code, etc.
#   Set false to disable for faster indexing on very large projects.
# index_refs = false

# index_embeddings: generate vector embeddings for semantic search.
#   On by default. Set false to disable for faster indexing.
# index_embeddings = false

# LLM and local-path settings belong in local.toml (gitignored).
# See local.toml for ollama_url, model, db_dir, etc.
"""

_PROJECT_LOCAL_DEFAULTS_TEMPLATE = """\
# Local developer settings — NOT committed to git.
# Overrides values from config.toml where both define the same key.

[llm]
# enabled = false   # disable Ollama, return raw prompts for the agent to answer
# ollama_url = "http://localhost:11434"
# model = "qwen2.5-coder:14b"   # minimum 14B recommended — see global config for options
# num_ctx = 16384
# keep_alive = "10m"   # how long to keep model loaded in VRAM after each request
# timeout = 600.0   # HTTP timeout for Ollama requests in seconds (default 600)
# debug_log = "~/.fw-context/llm-debug.jsonl"   # write LLM prompts/responses to JSONL
# Embedding model for semantic_search.
# Pull with:  ollama pull <model>
# Uncomment exactly ONE of the sections below.
#
# ── Default: mxbai-embed-large (~670 MB VRAM, no GPU needed) ──
# embed_model = "mxbai-embed-large:latest"
# embed_query_prompt = "Represent this sentence for searching relevant passages: "
# embed_doc_prompt = ""
#
# ── Higher quality: qwen3-embedding:8b (~4.7 GB VRAM, GPU recommended) ──
# embed_model = "qwen3-embedding:8b"
# embed_query_prompt = "Retrieve C/C++ functions, types, symbols, and implementation code relevant to the query."
# embed_doc_prompt = ""
# analyze_symbols = true    # generate structured symbol descriptions (summary, inputs, outputs) — enabled by default
# analyze_vendor = false    # when true, also analyze vendor/SDK code (mbed-os, Zephyr, etc.) — can add hours

# ── Chat API — use OpenAI-compatible API for chat instead of local Ollama ──
# When set, chat calls are routed to this endpoint. Embedding still uses
# local Ollama (embed_model above). Format is auto-detected from the URL:
#   :11434 or /api/generate → Ollama native (keeps keep_alive, num_ctx, auto_pull)
#   /v1 or bare host       → OpenAI-compatible (DeepSeek, OpenAI, LiteLLM, vLLM, etc.)
# Examples:
#   chat_api_base = "https://api.deepseek.com/v1"   # DeepSeek
#   chat_api_base = "https://api.openai.com/v1"     # OpenAI
#   chat_api_base = "http://localhost:4000"          # LiteLLM proxy
#   chat_api_base = "http://localhost:8080/v1"       # llama.cpp
# chat_api_base = ""
# chat_api_key = ""   # Bearer token — required by most cloud APIs
# chat_api_format = "auto"   # "auto" | "ollama" | "openai" (override detection)

# Auto-pull models on 404 (Ollama only). Set true for auto-recovery in
# online environments. Set false (default) for intranet/offline — model
# pulls must be done explicitly via `ollama pull` or the agent flow.
# auto_pull = false

# Stream chat responses (both OpenAI-compatible and Ollama-native).
# When true, sends stream:true and consumes SSE chunks — keeps the HTTP
# connection alive with continuous data flow, avoiding reverse-proxy idle
# timeouts (nginx 60s, Cloudflare 100s). Default false — non-streaming is
# sufficient for local Ollama. When false, SSE responses are still
# auto-detected and parsed as a fallback.
# stream = false

[index]
# db_dir = "~/.fw-context/index"   # where to store the SQLite index database
"""


@dataclass
class LLMConfig:
    """LLM (Ollama) configuration for symbol analysis, search query generation, and embeddings.

    Attributes:
        enabled: Set False to disable all Ollama calls — tools return raw prompts
            for the agent to answer instead.
        ollama_url: Ollama API endpoint (must be a loopback address unless you
            accept that source-code snippets will be sent externally).
        model: Chat model for analysis and search query generation.
            Minimum 14B parameters recommended for C++ embedded code.
        embed_model: Embedding model for semantic search.
            Default ``mxbai-embed-large:latest`` (~670 MB VRAM, no GPU needed).
            For better quality with a GPU use ``qwen3-embedding:8b`` (~4.7 GB).
        embed_query_prompt: Instruction prepended to query text before embedding.
            Auto-detected from model prefix when empty.  ``mxbai-*`` uses
            ``"Represent this sentence for searching relevant passages: "``,
            ``qwen3-embedding*`` uses a code-specific retrieval instruction.
            Set explicitly in TOML to override or disable (empty string).
        embed_doc_prompt: Instruction prepended to symbol descriptions during
            indexing.  Most models work best with an empty doc prompt — only
            set when the model's training expects a per-document instruction.
        num_ctx: Context window size in tokens.
        timeout: HTTP request timeout in seconds for Ollama API calls.
            Default 600 s (10 min) — analysis batches with large prompts and
            ``num_predict=3000`` can take several minutes, especially when
            the model runs on CPU. Embed requests use ``timeout * 2``.
        debug_log: Optional path to a JSONL file for debugging LLM prompts/responses.
        keep_alive: How long Ollama keeps the model loaded in VRAM after a request.
            ``"10m"`` (default) means the model stays loaded for 10 minutes of
            inactivity before unloading.  During indexing (~40 back-to-back
            requests), this prevents per-request model loading (~2-5 s each).
            Set ``"0"`` to unload immediately (saves VRAM, adds latency).
            Set ``"-1"`` to keep loaded indefinitely.
        analyze_symbols: Generate per-symbol summaries, inputs, and outputs during indexing.
        analyze_vendor: When False (default), skip LLM analysis for vendor/SDK code
            (mbed-os, Zephyr, PlatformIO, etc.) — only project code is analyzed.
            Set True to analyze every indexed symbol regardless of origin.
        stream: When True, send ``stream: true`` and consume SSE chunks for chat
            requests (both OpenAI-compatible and Ollama-native paths).  Keeps the
            HTTP connection alive with continuous data flow, avoiding reverse-proxy
            idle timeouts (nginx default 60s, Cloudflare 100s).  Default False —
            non-streaming is simpler and sufficient for local Ollama.  When False,
            SSE responses are still auto-detected and parsed (Plan A fallback).
    """

    enabled: bool = True
    ollama_url: str = "http://localhost:11434"
    model: str = "qwen2.5-coder:14b"
    embed_model: str = "mxbai-embed-large:latest"
    embed_query_prompt: str = ""
    embed_doc_prompt: str = ""
    num_ctx: int = 16384
    timeout: float = 600.0
    keep_alive: str = "10m"
    debug_log: Path | None = None
    analyze_symbols: bool = True
    analyze_vendor: bool = False
    chat_api_base: str | None = None
    chat_api_key: str | None = None
    chat_api_format: str = "auto"
    auto_pull: bool = False
    stream: bool = False


def _apply_embed_prompt_defaults(llm_cfg: LLMConfig) -> None:
    """Set embed prompt defaults based on model prefix when the field is empty.

    Called by ``_from_dict`` after loading TOML — only fills defaults when
    the user hasn't explicitly configured a prompt value.
    """
    model_lower = llm_cfg.embed_model.lower()
    if llm_cfg.embed_query_prompt == "":
        if model_lower.startswith("qwen3-embedding"):
            llm_cfg.embed_query_prompt = (
                "Retrieve C/C++ functions, types, symbols, and implementation code relevant to the query."
            )
        elif model_lower.startswith("mxbai"):
            llm_cfg.embed_query_prompt = "Represent this sentence for searching relevant passages: "
    if llm_cfg.embed_doc_prompt == "":
        if model_lower.startswith("qwen3-embedding"):
            llm_cfg.embed_doc_prompt = ""
        elif model_lower.startswith("mxbai"):
            llm_cfg.embed_doc_prompt = ""


@dataclass
class IndexConfig:
    """Index storage and scoping configuration.

    Attributes:
        db_dir: Directory where per-project SQLite databases are stored.
        compile_commands: Path to compile_commands.json (relative to project root).
        config_header: Path to a build-generated configuration header (e.g.
            ``config.h``) for projects whose build system does not emit
            ``-include`` flags in compile_commands.json.  When set, the file
            is force-included in every translation unit via ``-include``.
            Useful for custom build systems where auto-detection fails.
        vendor_paths: Additional vendor/SDK directories (additive to auto-detection).
            Paths matching these patterns get ``is_project=0``.
        project_paths: Manual project directories that override auto-detection.
            Paths matching these patterns get ``is_project=1``, even if they
            would otherwise be detected as vendor/SDK.  Use absolute paths for
            directories outside the project root.
        index_refs: Build cross-reference index for call-graph tools
            (find_callers, find_call_path, etc.). Enabled by default.
        index_embeddings: Generate vector embeddings during indexing for
            semantic search. Enabled by default.
    """

    db_dir: Path = field(default_factory=lambda: Path.home() / ".fw-context" / "index")
    compile_commands: Path = field(default_factory=lambda: Path("compile_commands.json"))
    config_header: str = ""  # path to build-generated config.h for custom build systems
    vendor_paths: list[str] = field(default_factory=list)
    project_paths: list[str] = field(default_factory=list)
    index_refs: bool = True
    index_embeddings: bool = True


@dataclass
class ProjectMeta:
    """Optional project-level metadata.

    Attributes:
        name: Human-readable name for the project. Defaults to the directory
            name when not set.
        id: Stable unique project identifier (UUID4 hex, 32 chars).
            Generated by ``fw-context init``, stored in
            ``.fw-context/config.toml``.  Shared across the team via git.
    """

    name: str | None = None
    id: str | None = None


@dataclass
class CacheServerConfig:
    """Optional centralized LLM analysis cache server.

    When ``url`` is set, the ``CacheClient`` is created and used during
    ``fw-context index --analyze`` to check remote cache before calling
    Ollama and to upload results after analysis.

    Attributes:
        url: Base URL of the cache server (e.g. ``https://fw-cache.example.com``).
        token: Bearer token for authentication (read+write or read-only).
        batch_size: Maximum hashes/entries per HTTP request (default 100).
        force: When ``True``, sends ``X-Cache-Overwrite`` header on write
            requests (requires ``can_overwrite`` on the server).
    """

    url: str = ""
    token: str = ""
    batch_size: int = 100
    force: bool = False


@dataclass
class Config:
    """Top-level configuration container aggregating all sub-configs.

    Loaded from TOML files with hierarchy: built-in defaults → global
    (``~/.fw-context/config.toml``) → shared project (``.fw-context/config.toml``)
    → local project (``.fw-context/local.toml``).
    Later levels override earlier ones via deep merge.

    Attributes:
        project: Optional project metadata (name override).
        build: Build system settings for compile_commands.json generation.
        index: Index storage, scoping, and feature flags.
        llm: Ollama configuration for analysis and search.
    """

    project: ProjectMeta = field(default_factory=ProjectMeta)
    build: BuildConfig = field(default_factory=BuildConfig)
    index: IndexConfig = field(default_factory=IndexConfig)
    llm: LLMConfig = field(default_factory=LLMConfig)
    cache_server: CacheServerConfig | None = None


def _deep_merge(base: dict, override: dict) -> dict:
    result = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(result.get(k), dict):
            result[k] = _deep_merge(result[k], v)
        else:
            result[k] = v
    return result


def _from_dict(data: dict) -> Config:
    cfg = Config()

    if proj := data.get("project", {}):
        if name := proj.get("name"):
            cfg.project.name = name
        if pid := proj.get("id"):
            cfg.project.id = pid

    if build := data.get("build", {}):
        if system := build.get("system"):
            cfg.build.system = system
        if "clean" in build:
            cfg.build.clean = bool(build["clean"])
        if command := build.get("command"):
            cfg.build.command = command
        # Mbed OS
        if target := build.get("target"):
            cfg.build.target = target
        if toolchain := build.get("toolchain"):
            cfg.build.toolchain = toolchain
        if profile := build.get("profile"):
            cfg.build.profile = profile
        if app_config := build.get("app_config"):
            cfg.build.app_config = app_config
        if extra := build.get("extra_profiles"):
            cfg.build.extra_profiles = list(extra)
        if defines := build.get("defines"):
            cfg.build.defines = list(defines)
        # Zephyr
        if board := build.get("board"):
            cfg.build.board = board
        # ESP-IDF
        if idf_path := build.get("idf_path"):
            cfg.build.idf_path = idf_path
        # Arduino
        if fqbn := build.get("fqbn"):
            cfg.build.fqbn = fqbn
        # Generic CMake
        if cmake_generator := build.get("cmake_generator"):
            cfg.build.cmake_generator = cmake_generator
        # Keil MDK
        if keil_project := build.get("keil_project"):
            cfg.build.keil_project = keil_project
        if keil_target := build.get("keil_target"):
            cfg.build.keil_target = keil_target
        if keil_cmsis_path := build.get("keil_cmsis_path"):
            cfg.build.keil_cmsis_path = keil_cmsis_path
        # IAR EWARM
        if iar_project := build.get("iar_project"):
            cfg.build.iar_project = iar_project
        if iar_target := build.get("iar_target"):
            cfg.build.iar_target = iar_target
        # Makefile
        if makefile := build.get("makefile"):
            cfg.build.makefile = makefile
        if make_target := build.get("make_target"):
            cfg.build.make_target = make_target
        if make_vars := build.get("make_vars"):
            cfg.build.make_vars = dict(make_vars)
        if "make_dry_run" in build:
            cfg.build.make_dry_run = bool(build["make_dry_run"])
        # Toolchain
        if toolchain_path := build.get("toolchain_path"):
            cfg.build.toolchain_path = toolchain_path
        if toolchain_prefix := build.get("toolchain_prefix"):
            cfg.build.toolchain_prefix = toolchain_prefix
        # Manual / bare mode
        if include_dirs := build.get("include_dirs"):
            cfg.build.include_dirs = list(include_dirs)
        if system_include_dirs := build.get("system_include_dirs"):
            cfg.build.system_include_dirs = list(system_include_dirs)
        if extra_flags := build.get("extra_flags"):
            cfg.build.extra_flags = list(extra_flags)
        if source_dirs := build.get("source_dirs"):
            cfg.build.source_dirs = list(source_dirs)
        if compiler := build.get("compiler"):
            cfg.build.compiler = compiler
        # Pre-build hooks
        if pre_build := build.get("pre_build"):
            cfg.build.pre_build = pre_build

    if idx := data.get("index", {}):
        if db_dir := idx.get("db_dir"):
            cfg.index.db_dir = Path(db_dir).expanduser()
        if cc := idx.get("compile_commands"):
            cfg.index.compile_commands = Path(cc)
        if config_header := idx.get("config_header"):
            cfg.index.config_header = config_header
        if "vendor_paths" in idx:
            cfg.index.vendor_paths = idx["vendor_paths"]
        if "project_paths" in idx:
            cfg.index.project_paths = idx["project_paths"]
        if "index_refs" in idx:
            cfg.index.index_refs = bool(idx["index_refs"])
        if "index_embeddings" in idx:
            cfg.index.index_embeddings = bool(idx["index_embeddings"])

    if llm := data.get("llm", {}):
        if "enabled" in llm:
            cfg.llm.enabled = bool(llm["enabled"])
        if url := llm.get("ollama_url"):
            cfg.llm.ollama_url = url
        if model := llm.get("model"):
            cfg.llm.model = model
        if embed_model := llm.get("embed_model"):
            cfg.llm.embed_model = embed_model
        if embed_qp := llm.get("embed_query_prompt"):
            cfg.llm.embed_query_prompt = embed_qp
        if embed_dp := llm.get("embed_doc_prompt"):
            cfg.llm.embed_doc_prompt = embed_dp
        _apply_embed_prompt_defaults(cfg.llm)
        if num_ctx := llm.get("num_ctx"):
            cfg.llm.num_ctx = int(num_ctx)
        if timeout := llm.get("timeout"):
            cfg.llm.timeout = float(timeout)
        if keep_alive := llm.get("keep_alive"):
            cfg.llm.keep_alive = keep_alive
        if debug_log := llm.get("debug_log"):
            cfg.llm.debug_log = Path(debug_log).expanduser()
        if "analyze_symbols" in llm:
            cfg.llm.analyze_symbols = bool(llm["analyze_symbols"])
        if "analyze_vendor" in llm:
            cfg.llm.analyze_vendor = bool(llm["analyze_vendor"])
        if chat_base := llm.get("chat_api_base"):
            cfg.llm.chat_api_base = chat_base
        if chat_key := llm.get("chat_api_key"):
            cfg.llm.chat_api_key = chat_key
        if fmt := llm.get("chat_api_format"):
            cfg.llm.chat_api_format = fmt
        if "auto_pull" in llm:
            cfg.llm.auto_pull = bool(llm["auto_pull"])
        if "stream" in llm:
            cfg.llm.stream = bool(llm["stream"])

    if cs := data.get("cache_server", {}):
        cfg.cache_server = CacheServerConfig(
            url=cs.get("url", ""),
            token=cs.get("token", ""),
            batch_size=cs.get("batch_size", 100),
            force=cs.get("force", False),
        )

    return cfg


def _ensure_global_config() -> Path:
    path = _GLOBAL_CONFIG_PATH
    if not path.exists():
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_GLOBAL_DEFAULTS, encoding="utf-8")
        except (OSError, PermissionError) as e:
            import logging

            logging.getLogger(__name__).warning("Could not create global config %s: %s", path, e)
    return path


def update_global_config(fix: bool = False) -> None:
    """Check ``~/.fw-context/config.toml`` for missing template keys.

    When *fix* is True, append missing keys (commented out) to the file.
    New keys are added to the appropriate TOML section — the template's
    section headers are used to determine where each key belongs.
    Does NOT modify existing keys or their values.

    Returns nothing; prints status to stdout.
    """
    import re

    path = _GLOBAL_CONFIG_PATH
    if not path.exists():
        if fix:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_GLOBAL_DEFAULTS)
            print(f"  [fix] created {path}")
        else:
            print(f"  [info] {path} missing — run with --force to create")
        return

    existing_text = path.read_text(encoding="utf-8")

    # Parse template: collect (section, key) pairs with their original line text.
    template_entries: list[tuple[str, str]] = []  # (key, full_line)
    section_map: dict[str, str] = {}  # key → section
    current_section = ""
    for line in _GLOBAL_DEFAULTS.splitlines():
        header_m = re.match(r"^\[(\w+)\]", line)
        if header_m:
            current_section = header_m.group(1)
            continue
        key_m = re.match(r"^(#?\s*)(\w+)\s*=", line)
        if key_m:
            key = key_m.group(2)
            template_entries.append((key, line))
            section_map[key] = current_section or ""

    missing: list[str] = []
    for key, _line_text in template_entries:
        if not re.search(rf"^\s*#?\s*{key}\s*=", existing_text, re.MULTILINE):
            missing.append(key)

    if missing:
        if fix:
            missing_set = set(missing)
            current_section = ""
            appended_sections: set[str] = set()

            existing_sections: set[str] = set(
                re.findall(r"^\[(\w+)\]", existing_text, re.MULTILINE)
            )

            lines_to_append: list[str] = []
            existing_ends_with_newline = existing_text.endswith("\n")

            for key, line_text in template_entries:
                if key not in missing_set:
                    continue
                section = section_map.get(key, "")
                if section and section != current_section:
                    if section not in existing_sections and section not in appended_sections:
                        lines_to_append.append(f"\n[{section}]")
                        appended_sections.add(section)
                    elif section in existing_sections and section not in appended_sections:
                        lines_to_append.append("")
                        appended_sections.add(section)
                    current_section = section
                if not existing_ends_with_newline:
                    lines_to_append.append("")
                    existing_ends_with_newline = True
                lines_to_append.append(line_text)

            if lines_to_append:
                text = "\n".join(lines_to_append)
                with path.open("a", encoding="utf-8") as f:
                    f.write("\n" + text + "\n")
                print(f"  [fix] {path}: added {', '.join(missing)}")
        else:
            print(f"  [info] {path}: missing options: {', '.join(missing)}")
    else:
        print(f"  [ok] {path}")


def _ensure_project_config(project_root: Path) -> Path:
    config_dir = project_root / _PROJECT_CONFIG_DIR
    path = config_dir / _PROJECT_CONFIG_NAME
    if not path.exists():
        try:
            config_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(_PROJECT_DEFAULTS_TEMPLATE, encoding="utf-8")
        except (OSError, PermissionError) as e:
            import logging

            logging.getLogger(__name__).warning("Could not create project config %s: %s", path, e)
    return path


def _ensure_project_local_config(project_root: Path) -> Path:
    config_dir = project_root / _PROJECT_CONFIG_DIR
    path = config_dir / _PROJECT_LOCAL_CONFIG_NAME
    if not path.exists():
        try:
            config_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(_PROJECT_LOCAL_DEFAULTS_TEMPLATE, encoding="utf-8")
        except (OSError, PermissionError) as e:
            import logging

            logging.getLogger(__name__).warning("Could not create local config %s: %s", path, e)
    return path


def _is_loopback_url(url: str) -> bool:
    """True if *url*'s host is a loopback address.

    Uses ``ipaddress`` for robust IPv4/IPv6 detection, including shortened
    IPv6 formats (``0:0:0:0:0:0:0:1``, ``::1``) and IPv4-mapped IPv6.
    """
    import ipaddress
    from urllib.parse import urlparse

    host = (urlparse(url).hostname or "").lower()
    if host == "localhost":
        return True
    try:
        addr = ipaddress.ip_address(host)
        return addr.is_loopback
    except ValueError:
        return False


# Module-level config cache with mtime-based invalidation.
# load_config() is called 20+ times per MCP session; caching avoids redundant
# TOML parsing when config files haven't changed.
_config_cache: dict[tuple, tuple[float, Config]] = {}


def load(project_root: Path | None = None) -> Config:
    """Load merged config for the given project root.

    Creates default config files on first use.  TOML parse errors in user
    configs are logged and the built-in defaults are used instead — a broken
    config file must not prevent the MCP tools from loading.

    Results are cached per (global_path, proj_path, local_path) tuple and
    invalidated when any source file's mtime changes.
    """
    import logging

    log = logging.getLogger(__name__)
    data: dict = {}

    global_path = _ensure_global_config()
    proj_path = _ensure_project_config(project_root) if project_root is not None else None
    local_path = _ensure_project_local_config(project_root) if project_root is not None else None

    # Check mtime-based cache
    cache_key = (global_path, proj_path, local_path)
    if cache_key in _config_cache:
        cached_ts, cached_cfg = _config_cache[cache_key]
        # Check if any source file changed
        try:
            newest = max(p.stat().st_mtime for p in cache_key if p is not None)
            if newest <= cached_ts:
                return cached_cfg
        except OSError:
            pass  # File missing → reload

    try:
        data = tomllib.loads(global_path.read_text(encoding="utf-8"))
    except Exception:
        log.exception("Failed to parse %s — using defaults", global_path)

    if project_root is not None:
        assert proj_path is not None
        try:
            proj_data = tomllib.loads(proj_path.read_text(encoding="utf-8"))
            data = _deep_merge(data, proj_data)

            # Security: pre_build in committed config.toml is a risk — anyone
            # who can commit can run arbitrary shell commands on other devs'
            # machines.  pre_build should only be in local.toml (gitignored).
            if (proj_data.get("build") or {}).get("pre_build"):
                msg = (
                    "⚠ SECURITY: pre_build is set in .fw-context/config.toml "
                    "(committed).  This allows anyone with commit access to run "
                    "arbitrary shell commands.  Move pre_build to "
                    ".fw-context/local.toml (gitignored) instead."
                )
                log.warning(msg)
                print(msg, file=sys.stderr)
        except Exception:
            log.exception("Failed to parse %s — ignoring project config", proj_path)

        assert local_path is not None
        try:
            local_data = tomllib.loads(local_path.read_text(encoding="utf-8"))
            data = _deep_merge(data, local_data)
        except Exception:
            log.exception("Failed to parse %s — ignoring local config", local_path)

        # Security: a committed or local config can redirect LLM calls (which
        # include source-code snippets) to an arbitrary host. Warn loudly.
        final_url = (data.get("llm") or {}).get("ollama_url")
        if final_url and not _is_loopback_url(final_url):
            log.warning(
                "Config sets a non-local ollama_url (%s). "
                "Source-code snippets in LLM prompts will be sent to that host.",
                final_url,
            )
            print(
                f"⚠ WARNING: non-local ollama_url ({final_url}) — source code will be sent to an external host.",
                file=sys.stderr,
            )

        # Security: chat_api_base may point to an external cloud API.
        # Unlike ollama_url (which is typically local), chat_api_base is
        # explicitly chosen by the user for cloud access — so this is an
        # informational notice, not a loud warning.
        chat_base = (data.get("llm") or {}).get("chat_api_base")
        if chat_base and not _is_loopback_url(chat_base):
            print(
                f"ℹ Chat API set to external host ({chat_base}). "
                "Source code snippets in chat prompts will be sent to this endpoint.",
                file=sys.stderr,
            )

    cfg = _from_dict(data)
    cfg.index.db_dir = cfg.index.db_dir.expanduser().resolve()

    # Cache with current mtime
    try:
        newest_mtime = max(p.stat().st_mtime for p in cache_key if p is not None)
        _config_cache[cache_key] = (newest_mtime, cfg)
    except OSError:
        pass  # Can't cache if we can't stat files

    return cfg


def generate_project_id() -> str:
    """Generate a new project ID — UUID4 without hyphens (32 hex chars)."""
    import uuid

    return uuid.uuid4().hex


def derive_project_id(root: Path) -> str:
    """Return the project ID from ``.fw-context/config.toml``.

    The ID is generated by ``fw-context init`` and stored in the
    ``[project]`` section of the shared project config.  It is stable,
    team-shared via git, and independent of filesystem location.

    Raises:
        ProjectNotInitializedError: When the project has not been
            initialized — ``fw-context init`` has not been run.
    """
    cfg = load(project_root=root)
    if cfg.project.id:
        return cfg.project.id

    raise ProjectNotInitializedError(root)


def _write_project_id(project_root: Path, project_id: str) -> None:
    """Write ``id = "<project_id>"`` into ``[project]`` section of config.toml.

    Uses line-level editing to preserve comments and formatting.
    Creates the config file from the template if it doesn't exist yet.
    """
    config_path = project_root / _PROJECT_CONFIG_DIR / _PROJECT_CONFIG_NAME
    if not config_path.exists():
        _ensure_project_config(project_root)

    lines = config_path.read_text(encoding="utf-8").splitlines(keepends=True)
    in_project = False

    for i, line in enumerate(lines):
        if line.strip() == "[project]":
            in_project = True
            continue
        if in_project and line.strip().startswith("[") and line.strip() != "[project]":
            # Start of next section — insert before it
            lines.insert(i, f'id = "{project_id}"\n\n')
            break
        if in_project and (line.strip().startswith("id ") or line.strip().startswith("# id ")):
            # Replace existing id line (commented or not)
            lines[i] = f'id = "{project_id}"\n'
            break
    else:
        if in_project:
            # id not found, append at end of [project] section (end of file)
            lines.append(f'id = "{project_id}"\n')

    config_path.write_text("".join(lines), encoding="utf-8")


def _format_toml_value(key: str, value: object) -> str:
    """Format a key-value pair as a TOML line."""
    if isinstance(value, bool):
        val = "true" if value else "false"
    elif isinstance(value, int):
        val = str(value)
    elif isinstance(value, float):
        val = str(value)
    else:
        val = f'"{value}"'
    return f"{key} = {val}\n"


def _update_local_toml(project_root: Path, updates: dict[str, object]) -> None:
    """Update the ``[llm]`` section of ``<project>/.fw-context/local.toml``.

    Uses line-level editing to preserve comments and other sections.
    Creates the file from the template if it doesn't exist yet.

    Only writes to ``local.toml`` (gitignored, per-developer) — never
    touches the global config or the shared project ``config.toml``.

    Args:
        project_root: Project root directory.
        updates: Dict of ``{key: value}`` pairs to write.  ``None`` values
            are skipped (key is not written).  Supported value types:
            ``str``, ``bool``, ``int``, ``float``.
    """
    local_path = project_root / _PROJECT_CONFIG_DIR / _PROJECT_LOCAL_CONFIG_NAME
    if not local_path.exists():
        _ensure_project_local_config(project_root)

    lines = local_path.read_text(encoding="utf-8").splitlines(keepends=True)

    # Find [llm] section boundaries
    in_llm = False
    llm_start = -1
    llm_end = len(lines)

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == "[llm]":
            in_llm = True
            llm_start = i + 1
            continue
        if in_llm and stripped.startswith("[") and stripped != "[llm]":
            llm_end = i
            break

    # Filter out None values
    to_write = {k: v for k, v in updates.items() if v is not None}
    if not to_write:
        return

    if llm_start == -1:
        # No [llm] section — append one at the end of the file
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        lines.append("\n[llm]\n")
        llm_start = len(lines)
        llm_end = len(lines)

    # For each key: find and replace existing line, or insert before llm_end
    for key, value in to_write.items():
        found = False
        for i in range(llm_start, llm_end):
            stripped = lines[i].strip()
            if re.match(rf"^#?\s*{re.escape(key)}\s*=", stripped):
                lines[i] = _format_toml_value(key, value)
                found = True
                break
        if not found:
            lines.insert(llm_end, _format_toml_value(key, value))
            llm_end += 1

    local_path.write_text("".join(lines), encoding="utf-8")
