"""fw-context configuration loader.

Hierarchy (later overrides earlier):
  1. built-in defaults
  2. ~/.fw-context/config.toml           (global, per-user)
  3. <project>/.fw-context/config.toml   (project, shared — commit to git)
  4. <project>/.fw-context/local.toml    (project, local — gitignore)
"""

from __future__ import annotations

import ipaddress
import logging
import sys
import tomllib
from collections import OrderedDict
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlparse

from ..indexer.build import BuildConfig

log = logging.getLogger(__name__)

__all__ = [
    "CacheServerConfig", "Config", "LLMConfig", "IndexConfig", "ProjectMeta",
    "ProjectNotInitializedError", "derive_project_id", "generate_project_id", "load",
    "update_global_config",
]

# ── Embedding description format version — bump when the text changes ──
# desc-v1: original — "kind name : in class : in path : sig : doc : llm"
# desc-v2: body text appended for function/method/constructor/destructor
# desc-v3: file name prefix added
# desc-v4: contextual sentence format (flowing text vs token-boundary lists)
# desc-v5: multi-chunk embeddings with semantic body splitting (chunk_index,
#   Body [part N/M] markers), composite PK (symbol_id, chunk_index)
DESCRIPTION_VERSION = "desc-v5"


class ProjectNotInitializedError(RuntimeError):
    """Raised when a project has not been initialized with ``fw-context init``."""

    def __init__(self, root: Path) -> None:
        self.root = root
        super().__init__(
            f"Project at {root} is not initialized.\n"
            "Run 'fw-context init' in the project root to generate a project ID."
        )


_GLOBAL_CONFIG_PATH = Path.home() / ".fw-context" / "config.toml"
_PROJECT_CONFIG_DIR = ".fw-context"
_PROJECT_CONFIG_NAME = "config.toml"
_PROJECT_LOCAL_CONFIG_NAME = "local.toml"

_GLOBAL_DEFAULTS = """\
[index]
db_dir = "~/.fw-context/index"

[llm]
# enabled = false   # uncomment to disable Ollama — LLM-calling tools will return raw prompts
ollama_url = "http://localhost:11434"

# Chat model for symbolic analysis and search query generation.
# Minimum recommended: 14B parameters — smaller models produce inconsistent JSON
# and poor-quality descriptions for C++ embedded code.
#
# Recommended models (min. 14B parameters):
#   Local:
#     qwen2.5-coder:14b        (4.8 GB VRAM, balanced speed/quality)
#     deepseek-coder-v2:16b    (10 GB VRAM, strong code comprehension)
#     qwen2.5-coder:32b        (19 GB VRAM, best local quality)
#   Cloud (Ollama proxies to cloud APIs — "ollama pull <model>"):
#     qwen3-coder:480b-cloud         (coding-focused, best quality)
#     deepseek-v4-flash:cloud        (284B MoE, 13B active — great value)
#     gemini-3-flash-preview:latest-cloud   (fast, affordable)
#   See: https://ollama.com/search?c=cloud
model = "qwen2.5-coder:14b"
num_ctx = 16384
# keep_alive = "10m"   # how long to keep model loaded in VRAM after each request
# timeout = 600.0   # HTTP timeout for Ollama requests in seconds (default 600)
# debug_log = "~/.fw-context/llm-debug.jsonl"   # write LLM prompts/responses to JSONL

# Embedding model for semantic_search (auto-detected when not set).
# Auto-detect: GPU available → qwen3-embedding:8b, CPU-only → qwen3-embedding:0.6b.
# Set explicitly below to override.
# Pull with:  ollama pull <model>
#
# ── CPU-only, 32K context (~400 MB), 4096-d vectors ──
# embed_model = "qwen3-embedding:0.6b"
#
# ── CPU/GPU, 32K context (~2.4 GB), 5120-d vectors ──
# embed_model = "qwen3-embedding:4b"
#
# ── GPU, 8K context (~4.7 GB), 4096-d vectors ──
# embed_model = "qwen3-embedding:8b"
#
# ── Custom query/doc prompts (auto-detected per model, override if needed) ──
# embed_query_prompt = "Retrieve C/C++ functions, types, symbols, and implementation code relevant to the query."
# embed_doc_prompt = ""

analyze_symbols = true
"""

_PROJECT_DEFAULTS_TEMPLATE = """\
[project]
# name = "my-project"   # defaults to directory name
# id = ""               # auto-generated by 'fw-context init' — do not edit

[build]
# Build system auto-detection: scans for .mbed, west.yml, or platformio.ini.
# Set system explicitly when auto-detection fails or you need to force a specific one.
# system = "mbed-os"        # choices: mbed-os, zephyr, platformio
# clean = true              # always clean build before indexing (recommended)
# command = "bear -- make"  # full override — bypasses all detection

# ── Mbed OS ──────────────────────────────────────────────────────────────
# Most values are auto-detected from .mbed and custom_targets.json.
# Override them here when auto-detection is wrong or incomplete.
#
# target = "P_ECB_BOARD"
# toolchain = "GCC_ARM"
# profile = "develop"
# app_config = "mbed_app.json"
# extra_profiles = ["lto.json"]
# defines = ["VERSION_FW_MAJOR=4", "DEV"]  # extra -D macros passed to compiler

# ── Zephyr ───────────────────────────────────────────────────────────────
# board is REQUIRED — there is no safe auto-detection for Zephyr boards.
# Set system = "zephyr" if west.yml coexists with another build system marker.
#
# system = "zephyr"
# board = "nrf52840dk_nrf52840"

# ── PlatformIO ───────────────────────────────────────────────────────────
# Usually needs no extra config — pio run --target compiledb is enough.
# system = "platformio"

[index]
compile_commands = "compile_commands.json"
# Generate it with:  fw-context index --build  (auto-detects build system)
# config_header = "config/my_build_config.h"   # path to config.h for custom build systems
#vendor_paths = ["third_party", "vendor_libs"]
#project_paths = ["src/old_hal", "lib/muj_modul"]
#  Pro cesty MIMO project_root používejte ABSOLUTNÍ cesty:
#  project_paths = ["/home/user/esp/components/muj_fork"]

# index_refs: build a cross-reference / call graph.
#   On by default — enables find_callers, find_call_path, find_dead_code, etc.
#   Set false to disable for faster indexing on very large projects.
# index_refs = false

# index_embeddings: generate vector embeddings for semantic search.
#   On by default. Set false to disable for faster indexing.
# index_embeddings = false

# LLM and local-path settings belong in local.toml (gitignored).
# See local.toml for ollama_url, model, db_dir, etc.
"""

_PROJECT_LOCAL_DEFAULTS_TEMPLATE = """\
# Local developer settings — NOT committed to git.
# Overrides values from config.toml where both define the same key.

[llm]
# enabled = false   # disable Ollama, return raw prompts for the agent to answer
# ollama_url = "http://localhost:11434"
# model = "qwen2.5-coder:14b"   # minimum 14B recommended — see global config for options
# num_ctx = 16384
# keep_alive = "10m"   # how long to keep model loaded in VRAM after each request
# timeout = 600.0   # HTTP timeout for Ollama requests in seconds (default 600)
# debug_log = "~/.fw-context/llm-debug.jsonl"   # write LLM prompts/responses to JSONL
# Embedding model for semantic_search (auto-detected when not set).
# Auto-detect: GPU available → qwen3-embedding:8b, CPU-only → qwen3-embedding:0.6b.
# Set explicitly below to override.
# Pull with:  ollama pull <model>
#
# ── CPU-only, 32K context (~400 MB), 4096-d vectors ──
# embed_model = "qwen3-embedding:0.6b"
#
# ── CPU/GPU, 32K context (~2.4 GB), 5120-d vectors ──
# embed_model = "qwen3-embedding:4b"
#
# ── GPU, 8K context (~4.7 GB), 4096-d vectors ──
# embed_model = "qwen3-embedding:8b"
#
# ── Custom query/doc prompts (auto-detected per model, override if needed) ──
# embed_query_prompt = "Retrieve C/C++ functions, types, symbols, and implementation code relevant to the query."
# embed_doc_prompt = ""
# analyze_symbols = true    # generate structured symbol descriptions (summary, inputs, outputs) — enabled by default
# analyze_vendor = false    # when true, also analyze vendor/SDK code (mbed-os, Zephyr, etc.) — can add hours

[index]
# db_dir = "~/.fw-context/index"   # where to store the SQLite index database
"""


@dataclass
class LLMConfig:
    """LLM (Ollama) configuration for symbol analysis, search query generation, and embeddings.

    Attributes:
        enabled: Set False to disable all Ollama calls — tools return raw prompts
            for the agent to answer instead.
        ollama_url: Ollama API endpoint (must be a loopback address unless you
            accept that source-code snippets will be sent externally).
        model: Chat model for analysis and search query generation.
            Minimum 14B parameters recommended for C++ embedded code.
        embed_model: Embedding model for semantic search.
            Empty (default, ``""``) auto-detects: GPU available →
            ``qwen3-embedding:8b``, CPU-only → ``qwen3-embedding:0.6b``.
            Set explicitly to override (see config template for options).
        embed_query_prompt: Instruction prepended to query text before embedding.
            Auto-detected from model prefix when empty.  ``qwen3-embedding*`` uses
            a code-specific retrieval instruction, ``mxbai-*`` and ``ibm-granite/*``
            use ``"Represent this sentence for searching relevant passages: "``.
            Set explicitly in TOML to override or disable (empty string).
        embed_doc_prompt: Instruction prepended to symbol descriptions during
            indexing.  Most models work best with an empty doc prompt — only
            set when the model's training expects a per-document instruction.
        embed_dim: Override output embedding dimension for Matryoshka models.
            When set and smaller than the model's native dimension, vectors
            are truncated to this size and re-normalized.  E.g. set to 128
            for granite-embedding-r2 to get 6× smaller storage with only -1.6
            MTEB Code points loss.
        num_ctx: Context window size in tokens.
        timeout: HTTP request timeout in seconds for Ollama API calls.
            Default 600 s (10 min) — analysis batches with large prompts and
            ``num_predict=3000`` can take several minutes, especially when
            the model runs on CPU. Embed requests use ``timeout * 2``.
        debug_log: Optional path to a JSONL file for debugging LLM prompts/responses.
        keep_alive: How long Ollama keeps the model loaded in VRAM after a request.
            ``"10m"`` (default) means the model stays loaded for 10 minutes of
            inactivity before unloading.  During indexing (~40 back-to-back
            requests), this prevents per-request model loading (~2-5 s each).
            Set ``"0"`` to unload immediately (saves VRAM, adds latency).
            Set ``"-1"`` to keep loaded indefinitely.
        analyze_symbols: Generate per-symbol summaries, inputs, and outputs during indexing.
         analyze_vendor: When False (default), skip LLM analysis for vendor/SDK code
             (mbed-os, Zephyr, PlatformIO, etc.) — only project code is analyzed.
             Set True to analyze every indexed symbol regardless of origin.
         ollama_max_concurrent: Maximum concurrent in-flight Ollama HTTP calls per
             process.  Default 1 (serial, identical to a Lock).  Increase to 2–4
             for multi-client MCP transports (SSE/streamable) where embedding
             requests (small model, ~100 ms) can overlap without saturating the
             GPU.  Chat requests are GPU-heavy — keep this low.
    """
    enabled: bool = True
    ollama_url: str = "http://localhost:11434"
    model: str = "qwen2.5-coder:14b"
    embed_model: str = ""  # empty = auto-detect (GPU → qwen3:8b, CPU → qwen3:0.6b)
    embed_query_prompt: str = ""
    embed_doc_prompt: str = ""
    embed_dim: int | None = None
    num_ctx: int = 16384
    timeout: float = 600.0
    keep_alive: str = "10m"
    debug_log: Path | None = None
    analyze_symbols: bool = True
    analyze_vendor: bool = False
    reranker_model: str | None = None  # "cross-encoder/ms-marco-MiniLM-L6-v2" to enable
    ollama_max_concurrent: int = 1  # max concurrent Ollama HTTP calls (1=serial, 2–4 for SSE transport)

    def embed_key(self) -> str:
        """Return ``embed_model`` with description version for cache disambiguation.

        Returns ``"auto:desc-v5"`` when *embed_model* is empty (auto-detect not
        yet resolved — ``resolve_embed_model`` fills the field at config load time).
        """
        model = self.embed_model or "auto"
        return f"{model}:{DESCRIPTION_VERSION}"


def _apply_embed_prompt_defaults(llm_cfg: LLMConfig) -> None:
    """Set embed prompt defaults based on model prefix when the field is empty.

    Called by ``_from_dict`` after loading TOML — only fills defaults when
    the user hasn't explicitly configured a prompt value.
    """
    model_lower = llm_cfg.embed_model.lower()
    if llm_cfg.embed_query_prompt == "":
        if model_lower.startswith("qwen3-embedding"):
            llm_cfg.embed_query_prompt = (
                "Retrieve C/C++ functions, types, symbols, and implementation "
                "code relevant to the query."
            )
        elif model_lower.startswith("mxbai"):
            llm_cfg.embed_query_prompt = (
                "Represent this sentence for searching relevant passages: "
            )
        elif model_lower.startswith("ibm-granite"):
            llm_cfg.embed_query_prompt = (
                "Represent this sentence for searching relevant passages: "
            )
    if llm_cfg.embed_doc_prompt == "":
        if model_lower.startswith("qwen3-embedding"):
            llm_cfg.embed_doc_prompt = ""
        elif model_lower.startswith("mxbai"):
            llm_cfg.embed_doc_prompt = ""
        elif model_lower.startswith("ibm-granite"):
            llm_cfg.embed_doc_prompt = ""


@dataclass
class IndexConfig:
    """Index storage and scoping configuration.

    Attributes:
        db_dir: Directory where per-project SQLite databases are stored.
        compile_commands: Path to compile_commands.json (relative to project root).
        config_header: Path to a build-generated configuration header (e.g.
            ``config.h``) for projects whose build system does not emit
            ``-include`` flags in compile_commands.json.  When set, the file
            is force-included in every translation unit via ``-include``.
            Useful for custom build systems where auto-detection fails.
        vendor_paths: Additional vendor/SDK directories (additive to auto-detection).
            Paths matching these patterns get ``is_project=0``.
        project_paths: Manual project directories that override auto-detection.
            Paths matching these patterns get ``is_project=1``, even if they
            would otherwise be detected as vendor/SDK.  Use absolute paths for
            directories outside the project root.
        index_refs: Build cross-reference index for call-graph tools
            (find_callers, find_call_path, etc.). Enabled by default.
        index_embeddings: Generate vector embeddings during indexing for
            semantic search. Enabled by default.
        rerank_top_k: Number of candidates to feed to the cross-encoder
            reranker (default 50).
        min_dense_count: Minimum number of embedding results required to
            trust dense-only routing in ``AdaptiveFusionPhase``.  Below this
            threshold FTS5 is used as fallback.  Set higher for projects
            with immature embedding quality (default 3, tuned on zbox-ecb-fw).
    """
    db_dir: Path = field(default_factory=lambda: Path.home() / ".fw-context" / "index")
    compile_commands: Path = field(default_factory=lambda: Path("compile_commands.json"))
    config_header: str = ""  # path to build-generated config.h for custom build systems
    vendor_paths: list[str] = field(default_factory=list)
    project_paths: list[str] = field(default_factory=list)
    index_refs: bool = True
    index_embeddings: bool = True
    rerank_top_k: int = 50
    min_dense_count: int = 3
    max_symbol_body_lines: int = 1000


@dataclass
class ProjectMeta:
    """Optional project-level metadata.

    Attributes:
        name: Human-readable name for the project. Defaults to the directory
            name when not set.
        id: Stable unique project identifier (UUID4 hex, 32 chars).
            Generated by ``fw-context init``, stored in
            ``.fw-context/config.toml``.  Shared across the team via git.
    """
    name: str | None = None
    id: str | None = None


@dataclass
class CacheServerConfig:
    """Optional centralized LLM analysis cache server.

    When ``url`` is set, the ``CacheClient`` is created and used during
    ``fw-context index --analyze`` to check remote cache before calling
    Ollama and to upload results after analysis.

    Attributes:
        url: Base URL of the cache server (e.g. ``https://fw-cache.example.com``).
        token: Bearer token for authentication (read+write or read-only).
        batch_size: Maximum hashes/entries per HTTP request (default 100).
        force: When ``True``, sends ``X-Cache-Overwrite`` header on write
            requests (requires ``can_overwrite`` on the server).
    """
    url: str = ""
    token: str = ""
    batch_size: int = 100
    force: bool = False


@dataclass
class Config:
    """Top-level configuration container aggregating all sub-configs.

    Loaded from TOML files with hierarchy: built-in defaults → global
    (``~/.fw-context/config.toml``) → shared project (``.fw-context/config.toml``)
    → local project (``.fw-context/local.toml``).
    Later levels override earlier ones via deep merge.

    Attributes:
        project: Optional project metadata (name override).
        build: Build system settings for compile_commands.json generation.
        index: Index storage, scoping, and feature flags.
        llm: Ollama configuration for analysis and search.
    """
    project: ProjectMeta = field(default_factory=ProjectMeta)
    build: BuildConfig = field(default_factory=BuildConfig)
    index: IndexConfig = field(default_factory=IndexConfig)
    llm: LLMConfig = field(default_factory=LLMConfig)
    cache_server: CacheServerConfig | None = None

def _deep_merge(base: dict, override: dict) -> dict:
    result = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(result.get(k), dict):
            result[k] = _deep_merge(result[k], v)
        else:
            result[k] = v
    return result


def _safe_int(val, default: int = 0) -> int:
    try:
        return int(val)
    except (ValueError, TypeError):
        log.warning("Invalid int value %r — using default %d", val, default)
        return default


def _safe_float(val, default: float = 0.0) -> float:
    try:
        return float(val)
    except (ValueError, TypeError):
        log.warning("Invalid float value %r — using default %.3f", val, default)
        return default


def _from_dict(data: dict) -> Config:
    """Convert merged TOML dict to Config with field mapping tables.

    Each mapping entry: (toml_key, attr_name, converter).
    Converters: "str" | "bool" | "list" | "dict" | "path" | "int(N)" | "float(N)"
    """
    import logging
    log = logging.getLogger(__name__)
    cfg = Config()

    # ── [project] ──
    if proj := data.get("project", {}):
        for key, attr, conv in _PROJECT_FIELDS:
            if key in proj:
                setattr(cfg.project, attr, _convert(proj[key], conv))

    # ── [build] ──
    if build := data.get("build", {}):
        for key, attr, conv in _BUILD_FIELDS:
            if key in build:
                setattr(cfg.build, attr, _convert(build[key], conv))

    # ── [index] ──
    if idx := data.get("index", {}):
        for key, attr, conv in _INDEX_FIELDS:
            if key in idx:
                setattr(cfg.index, attr, _convert(idx[key], conv))

    # ── [llm] ──
    if llm := data.get("llm", {}):
        for key, attr, conv in _LLM_FIELDS:
            if key in llm:
                setattr(cfg.llm, attr, _convert(llm[key], conv))

    # Normalize sentinel values: -1 means "not set" for embed_dim
    if cfg.llm.embed_dim is not None and cfg.llm.embed_dim < 0:
        cfg.llm.embed_dim = None

    from ..llm.auto_model import resolve_embed_model
    resolve_embed_model(cfg.llm)
    _apply_embed_prompt_defaults(cfg.llm)

    # ── [cache_server] ──
    if cs := data.get("cache_server", {}):
        token = cs.get("token", "")
        if not token:
            token_file = Path.home() / ".fw-context" / ".cache_token"
            if token_file.exists():
                try:
                    token = token_file.read_text(encoding="utf-8").strip()
                except OSError:
                    pass
        cfg.cache_server = CacheServerConfig(
            url=cs.get("url", ""),
            token=token,
            batch_size=cs.get("batch_size", 100),
            force=cs.get("force", False),
        )

    # Warn about unknown top-level keys
    _KNOWN_SECTIONS = {"project", "build", "index", "llm", "cache_server"}
    for key in data:
        if key not in _KNOWN_SECTIONS:
            log.warning(
                "Unknown config section [%s] — check for typos (valid: %s)",
                key, ", ".join(sorted(_KNOWN_SECTIONS)),
            )

    return cfg


def _convert(value, conv: str):
    """Convert a TOML value using the converter specification."""
    if conv == "str":
        return value
    if conv == "bool":
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            v = value.strip().lower()
            if v in ("true", "yes", "1", "on"):
                return True
            if v in ("false", "no", "0", "off", ""):
                return False
        return bool(value)
    if conv == "list":
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            return [value]
        return list(value)
    if conv == "dict":
        return dict(value)
    if conv == "path":
        return Path(value).expanduser()
    if conv.startswith("int("):
        default = int(conv[4:-1])
        return _safe_int(value, default)
    if conv.startswith("float("):
        default = float(conv[6:-1])
        return _safe_float(value, default)
    return value  # fallback


# ── Field mapping tables ──

_PROJECT_FIELDS: list[tuple[str, str, str]] = [
    ("name", "name", "str"),
    ("id", "id", "str"),
]

_BUILD_FIELDS: list[tuple[str, str, str]] = [
    ("system", "system", "str"),
    ("clean", "clean", "bool"),
    ("command", "command", "str"),
    ("target", "target", "str"),
    ("toolchain", "toolchain", "str"),
    ("profile", "profile", "str"),
    ("app_config", "app_config", "str"),
    ("extra_profiles", "extra_profiles", "list"),
    ("defines", "defines", "list"),
    ("board", "board", "str"),
    ("idf_path", "idf_path", "str"),
    ("fqbn", "fqbn", "str"),
    ("cmake_generator", "cmake_generator", "str"),
    ("keil_project", "keil_project", "str"),
    ("keil_target", "keil_target", "str"),
    ("keil_cmsis_path", "keil_cmsis_path", "str"),
    ("iar_project", "iar_project", "str"),
    ("iar_target", "iar_target", "str"),
    ("makefile", "makefile", "str"),
    ("make_target", "make_target", "str"),
    ("make_vars", "make_vars", "dict"),
    ("make_dry_run", "make_dry_run", "bool"),
    ("toolchain_path", "toolchain_path", "str"),
    ("toolchain_prefix", "toolchain_prefix", "str"),
    ("include_dirs", "include_dirs", "list"),
    ("system_include_dirs", "system_include_dirs", "list"),
    ("extra_flags", "extra_flags", "list"),
    ("source_dirs", "source_dirs", "list"),
    ("compiler", "compiler", "str"),
    ("pre_build", "pre_build", "str"),
]

_INDEX_FIELDS: list[tuple[str, str, str]] = [
    ("db_dir", "db_dir", "path"),
    ("compile_commands", "compile_commands", "path"),
    ("config_header", "config_header", "str"),
    ("vendor_paths", "vendor_paths", "list"),
    ("project_paths", "project_paths", "list"),
    ("index_refs", "index_refs", "bool"),
    ("index_embeddings", "index_embeddings", "bool"),
    ("rerank_top_k", "rerank_top_k", "int(50)"),
    ("min_dense_count", "min_dense_count", "int(3)"),
    ("max_symbol_body_lines", "max_symbol_body_lines", "int(1000)"),
]

_LLM_FIELDS: list[tuple[str, str, str]] = [
    ("enabled", "enabled", "bool"),
    ("ollama_url", "ollama_url", "str"),
    ("model", "model", "str"),
    ("embed_model", "embed_model", "str"),
    ("embed_query_prompt", "embed_query_prompt", "str"),
    ("embed_doc_prompt", "embed_doc_prompt", "str"),
    ("embed_dim", "embed_dim", "int(-1)"),
    ("num_ctx", "num_ctx", "int(16384)"),
    ("timeout", "timeout", "float(600.0)"),
    ("keep_alive", "keep_alive", "str"),
    ("debug_log", "debug_log", "path"),
    ("analyze_symbols", "analyze_symbols", "bool"),
    ("analyze_vendor", "analyze_vendor", "bool"),
    ("reranker_model", "reranker_model", "str"),
    ("ollama_max_concurrent", "ollama_max_concurrent", "int(1)"),
]

def _ensure_global_config() -> Path:
    path = _GLOBAL_CONFIG_PATH
    if not path.exists():
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_GLOBAL_DEFAULTS)
        except (OSError, PermissionError) as e:
            import logging
            logging.getLogger(__name__).warning("Could not create global config %s: %s", path, e)
    return path


def update_global_config(fix: bool = False) -> None:
    """Check ``~/.fw-context/config.toml`` for missing template keys.

    When *fix* is True, merge missing keys from the template into the file.
    Keys are placed in their correct TOML sections.  Does NOT modify
    existing keys or their values.

    Returns nothing; prints status to stdout.
    """
    path = _GLOBAL_CONFIG_PATH
    if not path.exists():
        if fix:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_GLOBAL_DEFAULTS)
            print(f"  [fix] created {path}")
        else:
            print(f"  [info] {path} missing — run with --force to create")
        return

    from fw_context_mcp.config._toml_editor import merge_template

    added = merge_template(path, _GLOBAL_DEFAULTS)
    if added:
        if fix:
            print(f"  [fix] {path}: added {', '.join(added)}")
        else:
            print(f"  [info] {path}: missing options: {', '.join(added)}")
    else:
        print(f"  [ok] {path}")


def _ensure_project_config(project_root: Path) -> Path:
    config_dir = project_root / _PROJECT_CONFIG_DIR
    path = config_dir / _PROJECT_CONFIG_NAME
    if not path.exists():
        try:
            config_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(_PROJECT_DEFAULTS_TEMPLATE)
        except (OSError, PermissionError) as e:
            import logging
            logging.getLogger(__name__).warning("Could not create project config %s: %s", path, e)
    return path


def _ensure_project_local_config(project_root: Path) -> Path:
    config_dir = project_root / _PROJECT_CONFIG_DIR
    path = config_dir / _PROJECT_LOCAL_CONFIG_NAME
    if not path.exists():
        try:
            config_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(_PROJECT_LOCAL_DEFAULTS_TEMPLATE)
        except (OSError, PermissionError) as e:
            import logging
            logging.getLogger(__name__).warning("Could not create local config %s: %s", path, e)
    return path


def _is_loopback_url(url: str) -> bool:
    """True if *url*'s host is a loopback address.

    Uses ``ipaddress`` for robust IPv4/IPv6 detection, including shortened
    IPv6 formats (``0:0:0:0:0:0:0:1``, ``::1``) and IPv4-mapped IPv6.
    """

    host = (urlparse(url).hostname or "").lower()
    if host == "localhost":
        return True
    try:
        addr = ipaddress.ip_address(host)
        return addr.is_loopback
    except ValueError:
        return False


# Module-level config cache with mtime-based invalidation.
# load_config() is called 20+ times per MCP session; caching avoids redundant
# TOML parsing when config files haven't changed.
_config_cache: OrderedDict[tuple, tuple[float, Config]] = OrderedDict()
_CONFIG_CACHE_MAX = 50


def load(project_root: Path | None = None) -> Config:
    """Load merged config for the given project root.

    Creates default config files on first use.  TOML parse errors in user
    configs are logged and the built-in defaults are used instead — a broken
    config file must not prevent the MCP tools from loading.

    Results are cached per (global_path, proj_path, local_path) tuple and
    invalidated when any source file's mtime changes.
    """
    import logging

    log = logging.getLogger(__name__)
    data: dict = {}

    global_path = _ensure_global_config()
    proj_path = _ensure_project_config(project_root) if project_root is not None else None
    local_path = _ensure_project_local_config(project_root) if project_root is not None else None

    # Check mtime-based cache
    cache_key = (global_path, proj_path, local_path)
    if cache_key in _config_cache:
        cached_ts, cached_cfg = _config_cache[cache_key]
        # Check if any source file changed
        try:
            newest = max(
                p.stat().st_mtime for p in cache_key if p is not None
            )
            if newest <= cached_ts:
                return cached_cfg
        except OSError:
            pass  # File missing → reload

    try:
        data = tomllib.loads(global_path.read_text())
    except (OSError, ValueError):
        log.exception("Failed to parse %s — using defaults", global_path)

    if project_root is not None:
        assert proj_path is not None
        try:
            proj_data = tomllib.loads(proj_path.read_text())
            data = _deep_merge(data, proj_data)
        except (OSError, ValueError):
            log.exception("Failed to parse %s — ignoring project config", proj_path)

        # Security: pre_build in committed config.toml is a risk — anyone
        # who can commit can run arbitrary shell commands on other devs'
        # machines.  pre_build should only be in local.toml (gitignored).
        if (proj_data.get("build") or {}).get("pre_build"):
            msg = (
                "⚠ SECURITY: pre_build is set in .fw-context/config.toml "
                "(committed).  This allows anyone with commit access to run "
                "arbitrary shell commands.  Move pre_build to "
                ".fw-context/local.toml (gitignored) instead."
            )
            log.warning(msg)
            print(msg, file=sys.stderr)

        assert local_path is not None
        try:
            local_data = tomllib.loads(local_path.read_text())
            data = _deep_merge(data, local_data)
        except (OSError, ValueError):
            log.exception("Failed to parse %s — ignoring local config", local_path)

        # Security: a committed or local config can redirect LLM calls (which
        # include source-code snippets) to an arbitrary host. Warn loudly.
        final_url = (data.get("llm") or {}).get("ollama_url")
        if final_url and not _is_loopback_url(final_url):
            log.warning(
                "Config sets a non-local ollama_url (%s). "
                "Source-code snippets in LLM prompts will be sent to that host.",
                final_url,
            )
            print(
                f"⚠ WARNING: non-local ollama_url ({final_url}) — "
                "source code will be sent to an external host.",
                file=sys.stderr,
            )

    cfg = _from_dict(data)
    cfg.index.db_dir = cfg.index.db_dir.expanduser().resolve()

    # Cache with current mtime
    try:
        newest_mtime = max(
            p.stat().st_mtime for p in cache_key if p is not None
        )
        if len(_config_cache) >= _CONFIG_CACHE_MAX:
            _config_cache.popitem(last=False)
        _config_cache[cache_key] = (newest_mtime, cfg)
    except OSError:
        pass  # Can't cache if we can't stat files

    return cfg


def generate_project_id() -> str:
    """Generate a new project ID — UUID4 without hyphens (32 hex chars)."""
    import uuid

    return uuid.uuid4().hex


def derive_project_id(root: Path) -> str:
    """Return the project ID from ``.fw-context/config.toml``.

    The ID is generated by ``fw-context init`` and stored in the
    ``[project]`` section of the shared project config.  It is stable,
    team-shared via git, and independent of filesystem location.

    Raises:
        ProjectNotInitializedError: When the project has not been
            initialized — ``fw-context init`` has not been run.
    """
    cfg = load(project_root=root)
    if cfg.project.id:
        return cfg.project.id

    raise ProjectNotInitializedError(root)


def _write_project_id(project_root: Path, project_id: str) -> None:
    """Write ``id = "<project_id>"`` into ``[project]`` section of config.toml.

    Uses :func:`fw_context_mcp.config._toml_editor.set_key` for atomic,
    section-aware writes.  Creates the config file from the template if it
    doesn't exist yet.
    """
    config_path = project_root / _PROJECT_CONFIG_DIR / _PROJECT_CONFIG_NAME
    if not config_path.exists():
        _ensure_project_config(project_root)

    from fw_context_mcp.config._toml_editor import set_key

    set_key(config_path, "project", "id", project_id)
