"""PlatformIO build system — detection, build, validation, and auto-fix."""

from __future__ import annotations

import configparser
import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from . import registry
from .protocol import BuildIssue

if TYPE_CHECKING:
    from ..build import BuildConfig

log = logging.getLogger(__name__)

_PIO_MARKERS = ["platformio.ini"]


class PlatformIOBuildSystem:
    """PlatformIO build system (``pio run --target compiledb``)."""

    name: str = "PlatformIO"
    config_key: str = "platformio"
    markers: list[str] = ["platformio.ini"]

    # ── Detection ──

    @classmethod
    def detect(cls, project_root: Path) -> bool:
        root = project_root.resolve()
        return any((root / m).exists() for m in _PIO_MARKERS)

    # ── Build ──

    def build(self, project_root: Path, cfg: BuildConfig) -> Path:
        """Generate compile_commands.json via ``pio run --target compiledb``."""
        if not shutil.which("pio") and not shutil.which("platformio"):
            raise RuntimeError(
                "PlatformIO CLI is required.  Install it:  pip install platformio"
            )

        pio_bin = "pio" if shutil.which("pio") else "platformio"

        cmd: list[str] = [pio_bin, "run", "--project-dir", str(project_root), "--target", "compiledb"]

        if cfg.clean:
            clean_cmd = [pio_bin, "run", "--project-dir", str(project_root), "--target", "clean"]
            log.info("platformio clean: %s", " ".join(clean_cmd))
            subprocess.run(clean_cmd, cwd=project_root)

        log.info("platformio build: %s", " ".join(cmd))
        result = subprocess.run(cmd, cwd=project_root)

        if result.returncode != 0:
            raise RuntimeError(f"pio run --target compiledb failed with exit code {result.returncode}")

        cc_path = project_root / "compile_commands.json"
        if not cc_path.exists():
            raise RuntimeError("compile_commands.json was not generated — pio run may have failed silently")

        return cc_path

    # ── Dep tracking ──

    def ensure_dep_tracking(self, project_root: Path, *, fix: bool = False) -> list[str]:
        """Ensure the PlatformIO project generates ``.d`` dependency files.

        PlatformIO toolchains that don't pass ``-MMD`` by default (STM32, etc.)
        produce no ``.d`` files, which prevents fw-context from detecting header
        changes.  This configures the project to pull ``-MMD`` from a shared
        config file so every platform benefits.

        In fix mode (*fix=True*):
        1. Creates ``~/.fw-context/platformio-shared.ini`` with ``-MMD``.
        2. Adds ``[platformio] extra_configs`` referencing the shared file.
        3. Appends ``$\\{common.build_flags}`` to each ``[env:*]`` section.
        """
        shared_dir = Path.home() / ".fw-context"
        shared_ini = shared_dir / "platformio-shared.ini"
        pio_ini = project_root / "platformio.ini"

        if not pio_ini.exists():
            return []

        messages: list[str] = []

        # ── 1. Ensure shared config exists ──
        shared_content = (
            "; Shared PlatformIO configuration — header dependency tracking for fw-context.\n"
            "; Generated by fw-context.  Include in each project with:\n"
            ";   [platformio]\n"
            ";   extra_configs = ~/.fw-context/platformio-shared.ini\n"
            ";   [env:xxx]\n"
            ";   build_flags = ${common.build_flags} ...your flags...\n"
            "\n"
            "[common]\n"
            "build_flags = -MMD\n"
        )
        if fix:
            try:
                shared_dir.mkdir(parents=True, exist_ok=True)
                if not shared_ini.exists():
                    shared_ini.write_text(shared_content, encoding="utf-8")
                    messages.append(f"[+] {shared_ini}")
            except (OSError, PermissionError) as exc:
                log.warning("Could not write %s: %s", shared_ini, exc)
                return messages
        elif not shared_ini.exists():
            messages.append(f"  [info] shared config missing, would create: {shared_ini}")

        # ── 2. Parse platformio.ini with configparser ──
        try:
            raw = pio_ini.read_text(encoding="utf-8")
        except (OSError, PermissionError) as exc:
            log.warning("Could not read %s: %s", pio_ini, exc)
            return messages

        parser = configparser.ConfigParser(interpolation=None)
        parser.read_string(raw)

        needs_fix = False
        extra_configs_line = "extra_configs = ~/.fw-context/platformio-shared.ini"
        shared_build_flags_ref = "${common.build_flags}"

        # Check [platformio] section
        if parser.has_section("platformio"):
            current_extra = parser.get("platformio", "extra_configs", fallback="")
            if "platformio-shared.ini" not in current_extra:
                needs_fix = True
        else:
            needs_fix = True

        # Check each [env:*] section has ${common.build_flags}
        if not needs_fix:
            for section in parser.sections():
                if section.startswith("env:") or section == "env":
                    build_flags = parser.get(section, "build_flags", fallback="")
                    if shared_build_flags_ref not in build_flags:
                        needs_fix = True
                        break

        if not needs_fix:
            messages.append(f"  [ok] {pio_ini} already configured for dep tracking")
            return messages

        if not fix:
            messages.append(f"  [info] {pio_ini}: would add extra_configs + build_flags = {shared_build_flags_ref}")
            return messages

        # ── 3. Modify and write ──
        lines = raw.splitlines(keepends=True)
        result: list[str] = []

        has_platformio_section = bool(re.search(r"(?m)^\[platformio\]", raw))
        updated_sections: set[str] = set()

        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.rstrip("\n").rstrip("\r")

            section_match = re.match(r"^\[(env(?::\S+)?|platformio)\]", stripped)
            if section_match:
                section_name = section_match.group(1)
                result.append(line)
                i += 1
                updated_sections.add(section_name)

                if section_name == "platformio":
                    if "extra_configs" not in raw:
                        result.append(f"{extra_configs_line}\n")
                        has_platformio_section = True

                elif section_name.startswith("env"):
                    has_build_flags = False
                    scan = i
                    while scan < len(lines):
                        sline = lines[scan].rstrip("\n").rstrip("\r")
                        if sline.startswith("[") or scan >= i + 20:
                            break
                        if sline.startswith("build_flags"):
                            has_build_flags = True
                            if shared_build_flags_ref not in sline:
                                indent = len(sline) - len(sline.lstrip())
                                lines[scan] = (
                                    f"{' ' * indent}build_flags = "
                                    f"{shared_build_flags_ref} {sline.split('=', 1)[1].strip()}\n"
                                )
                            break
                        scan += 1
                    if not has_build_flags:
                        result.append(f"build_flags = {shared_build_flags_ref}\n")
                continue

            result.append(line)
            i += 1

        if not has_platformio_section:
            result.insert(0, f"\n[platformio]\n{extra_configs_line}\n")

        try:
            pio_ini.write_text("".join(result), encoding="utf-8")
            messages.append(f"  [+] {pio_ini}: added dep tracking (extra_configs + -MMD)")
        except (OSError, PermissionError) as exc:
            log.warning("Could not write %s: %s", pio_ini, exc)

        return messages

    # ── Validation ──

    def validate_artifacts(self, compile_commands: Path, project_root: Path) -> list[BuildIssue]:
        return []

    # ── Auto-fix ──

    def auto_fix(self, issue: BuildIssue, project_root: Path) -> bool:
        return False

    # ── Tools ──

    def required_tools(self) -> list[str]:
        return ["pio"]


# Register
registry.register(PlatformIOBuildSystem)
