"""SQLite storage layer for fw-context-mcp index."""

from __future__ import annotations

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "DatabaseCorruptionError",
    "FileHashRecord",
    "WriteLockTimeout",
    "_cosine_sim",
    "_ensure_column",
    "_expand_query",
    "count_fp_assignments",
    "count_indirect_call_sites",
    "count_llm_analysis",
    "count_refs",
    "delete_build_data",
    "delete_fp_assignments_for_file",
    "delete_inheritance_for_file",
    "delete_indirect_call_sites_for_file",
    "delete_macros_for_file",
    "delete_orphan_files",
    "delete_refs_for_file",
    "delete_symbols_for_file",
    "drop_fts_triggers",
    "ensure_schema",
    "find_all_callers_recursive",
    "find_callees_recursive",
    "find_call_path",
    "find_dead_code",
    "find_hotspots",
    "find_indirect_call_sites",
    "find_indirect_targets",
    "find_macro_refs",
    "find_refs",
    "get_active_config",
    "get_all_builds_for_project",
    "get_all_projects",
    "get_build_stats",
    "get_class_members",
    "get_db_schema_version",
    "get_direct_bases",
    "get_direct_bases_batch",
    "get_direct_derived",
    "get_direct_derived_batch",
    "get_embeddings",
    "clean_orphan_embeddings",
    "clean_orphan_embeddings_vec",
    "get_file_hashes",
    "get_file_map",
    "get_file_mtime_indexed",
    "get_file_mtimes",
    "get_llm_analysis_for_symbol",
    "get_overrides_for_method",
    "get_template_instances",
    "init_vec_table",
    "insert_fp_assignments_batch",
    "insert_indirect_call_sites_batch",
    "insert_inheritance_batch",
    "insert_macros_batch",
    "insert_overrides_batch",
    "insert_refs_batch",
    "insert_symbols_batch",
    "lookup_macro",
    "open_db",
    "rebuild_files_fts",
    "rebuild_fts",
    "rebuild_macros_fts",
    "search_similar_hybrid",
    "search_similar_vec",
    "search_symbols",
    "split_tokens",
    "transaction",
    "upsert_build_config",
    "upsert_embeddings",
    "upsert_embeddings_vec",
    "upsert_file",
    "upsert_llm_analysis_batch",
    "upsert_project",
    "write_lock",
]

import logging

from ._callgraph import (
    find_all_callers_recursive,
    find_call_path,
    find_callees_recursive,
    find_dead_code,
    find_hotspots,
)
from ._connection import (
    DatabaseCorruptionError,
    ensure_schema,
    get_db_schema_version,
    open_db,
    transaction,
)
from ._locking import WriteLockTimeout, write_lock
from ._embeddings import (
    _cosine_sim,
    get_embeddings,
    clean_orphan_embeddings,
    clean_orphan_embeddings_vec,
    init_vec_table,
    search_similar_hybrid,
    search_similar_vec,
    upsert_embeddings,
    upsert_embeddings_vec,
)
from ._files import (
    FileHashRecord,
    delete_orphan_files,
    delete_symbols_for_file,
    get_file_hashes,
    get_file_map,
    get_file_mtime_indexed,
    get_file_mtimes,
    upsert_file,
)
from ._fts import (
    rebuild_files_fts,
    rebuild_fts,
    rebuild_macros_fts,
)
from ._inheritance import (
    delete_inheritance_for_file,
    get_class_members,
    get_direct_bases,
    get_direct_bases_batch,
    get_direct_derived,
    get_direct_derived_batch,
    get_overrides_for_method,
    get_template_instances,
    insert_inheritance_batch,
    insert_overrides_batch,
)
from ._llm import (
    count_llm_analysis,
    get_llm_analysis_for_symbol,
    upsert_llm_analysis_batch,
)
from ._projects import (
    delete_build_data,
    get_active_config,
    get_all_builds_for_project,
    get_all_projects,
    get_build_stats,
    upsert_build_config,
    upsert_project,
)
from ._refs import (
    count_fp_assignments,
    count_indirect_call_sites,
    count_refs,
    delete_fp_assignments_for_file,
    delete_indirect_call_sites_for_file,
    delete_refs_for_file,
    find_indirect_call_sites,
    find_indirect_targets,
    find_refs,
    insert_fp_assignments_batch,
    insert_indirect_call_sites_batch,
    insert_refs_batch,
)
from ._schema import (
    CURRENT_SCHEMA_VERSION,
    _ensure_column,
    drop_fts_triggers,
)
from ._symbols import (
    _expand_query,
    delete_macros_for_file,
    find_macro_refs,
    insert_macros_batch,
    insert_symbols_batch,
    lookup_macro,
    search_symbols,
    split_tokens,
)

log = logging.getLogger(__name__)
