"""Nginx configuration helper for the cache server.

Detects existing nginx state, generates reverse-proxy configuration,
and manages Let's Encrypt certificates via certbot.
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

NGINX_SITES_AVAILABLE = Path("/etc/nginx/sites-available")
NGINX_SITES_ENABLED = Path("/etc/nginx/sites-enabled")
NGINX_CONFIG_NAME = "fw-cache"

# Domain name validation — rejects shell metacharacters and path components
_DOMAIN_RE = re.compile(r'^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$')


def _validate_domain(domain: str) -> None:
    """Raise ValueError if *domain* is not a valid DNS name.

    Rejects strings containing shell metacharacters, newlines, semicolons,
    path separators, or other characters that could be used for injection
    into nginx configuration or filesystem paths.
    """
    if not domain or not _DOMAIN_RE.match(domain):
        raise ValueError(
            f"Invalid domain: {domain!r}. "
            "Domain must be a valid DNS name (e.g. fw-cache.example.com)."
        )


def detect_nginx() -> dict[str, Any]:
    """Detect the current nginx state on the system.

    Returns a dict with keys:
        installed (bool), running (bool), has_https (bool), domains (list[str])
    """
    result: dict[str, Any] = {"installed": False, "running": False, "has_https": False, "domains": []}

    # Check if nginx binary exists
    nginx_bin = shutil.which("nginx")
    if not nginx_bin:
        return result
    result["installed"] = True

    # Check if nginx is running
    try:
        subprocess.run(["systemctl", "is-active", "--quiet", "nginx"], check=True, timeout=5)
        result["running"] = True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        log.debug("Failed to check nginx running state", exc_info=True)

    # Detect existing HTTPS configs
    if NGINX_SITES_ENABLED.exists():
        for conf in NGINX_SITES_ENABLED.iterdir():
            if conf.is_symlink() or conf.is_file():
                try:
                    content = conf.read_text()
                    if "listen 443 ssl" in content or "listen [::]:443 ssl" in content:
                        result["has_https"] = True
                        # Extract server_name
                        for line in content.splitlines():
                            line = line.strip()
                            if not line.lstrip().startswith("#") and line.startswith("server_name ") and ";" in line:
                                names = line.replace("server_name ", "").replace(";", "").split()
                                result["domains"].extend(names)
                except OSError:
                    log.debug("Failed to read nginx config %s", conf, exc_info=True)

    return result


def detect_certbot() -> dict[str, Any]:
    """Check certbot availability.

    Returns a dict with keys:
        installed (bool), has_certificates (bool)
    """
    result: dict[str, Any] = {"installed": False, "has_certificates": False}

    if shutil.which("certbot"):
        result["installed"] = True

    cert_dir = Path("/etc/letsencrypt/live")
    try:
        if cert_dir.exists() and any(cert_dir.iterdir()):
            result["has_certificates"] = True
    except PermissionError:
        # Can't read without sudo — assume certs may exist
        result["has_certificates"] = True

    return result


def generate_nginx_config(domain: str, proxy_port: int = 8000) -> str:
    """Generate an nginx site configuration for reverse-proxying the cache server.

    The configuration enables HTTPS on port 443 with HTTP/1.1 keep-alive,
    sets appropriate proxy headers, and includes rate limiting at 50 req/s
    with a burst of 20.

    ``limit_req_zone`` is written separately to
    ``/etc/nginx/conf.d/fw-cache-rate-limit.conf`` by
    :func:`write_nginx_config` — it must reside in the ``http`` block,
    which is not available inside ``sites-available/`` configs on
    non-Debian systems.
    """
    _validate_domain(domain)
    return f"""# fw-context Cache Server — nginx reverse proxy
# Generated by fw-cache-server setup

upstream fw_cache_backend {{
    server 127.0.0.1:{proxy_port};
    keepalive 32;
}}

server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    limit_req zone=fw_context_cache burst=20 nodelay;

    location / {{
        proxy_pass http://fw_cache_backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


def write_nginx_config(domain: str, proxy_port: int = 8000) -> Path:
    """Write the nginx config file via sudo and return its path.

    Also writes ``limit_req_zone`` to
    ``/etc/nginx/conf.d/fw-cache-rate-limit.conf`` so the directive
    always resides in the ``http`` block regardless of distribution.
    """
    import subprocess
    config_text = generate_nginx_config(domain, proxy_port)
    config_path = NGINX_SITES_AVAILABLE / NGINX_CONFIG_NAME
    try:
        subprocess.run(
            ["sudo", "tee", str(config_path)],
            input=config_text, text=True, capture_output=True, timeout=10, check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"Failed to write {config_path} — write it manually: {e}", file=sys.stderr)
        print(config_text)

    # Write rate-limit zone to conf.d/ — must be in http block
    rate_limit_conf = "limit_req_zone $binary_remote_addr zone=fw_context_cache:10m rate=50r/s;\n"
    rate_limit_path = Path("/etc/nginx/conf.d/fw-cache-rate-limit.conf")
    try:
        subprocess.run(
            ["sudo", "tee", str(rate_limit_path)],
            input=rate_limit_conf, text=True, capture_output=True, timeout=10, check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"Failed to write {rate_limit_path} — write it manually: {e}", file=sys.stderr)

    return config_path


def enable_nginx_site() -> None:
    """Create a symlink from sites-available to sites-enabled via sudo."""
    import subprocess
    src = str(NGINX_SITES_AVAILABLE / NGINX_CONFIG_NAME)
    dst = str(NGINX_SITES_ENABLED / NGINX_CONFIG_NAME)
    try:
        subprocess.run(["sudo", "ln", "-sf", src, dst], check=True, timeout=10)
    except subprocess.CalledProcessError as e:
        print(f"Failed to enable site — run: sudo ln -s {src} {dst} ({e})", file=sys.stderr)


def test_nginx_config() -> bool:
    """Run ``nginx -t`` to validate configuration.  Returns True on success."""
    try:
        subprocess.run(["sudo", "nginx", "-t"], check=True, capture_output=True, text=True, timeout=10)
        return True
    except subprocess.CalledProcessError as e:
        print("nginx config test failed:", e.stderr, file=sys.stderr)
        return False
    except FileNotFoundError:
        print("nginx not found — cannot test config", file=sys.stderr)
        return False


def reload_nginx() -> bool:
    """Reload nginx.  Returns True on success."""
    try:
        subprocess.run(["systemctl", "reload", "nginx"], check=True, timeout=10)
        return True
    except subprocess.CalledProcessError:
        try:
            subprocess.run(["nginx", "-s", "reload"], check=True, timeout=10)
            return True
        except subprocess.CalledProcessError:
            return False


def cert_exists(domain: str) -> bool:
    """Check if a Let's Encrypt certificate exists for *domain* (via sudo)."""
    _validate_domain(domain)
    import subprocess
    cert_path = f"/etc/letsencrypt/live/{domain}/fullchain.pem"
    try:
        result = subprocess.run(
            ["sudo", "test", "-f", cert_path],
            capture_output=True, timeout=5,
        )
        return result.returncode == 0
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False


def obtain_certificate(domain: str, email: str = "", expand: bool = False) -> bool:
    """Obtain or expand a Let's Encrypt certificate via certbot.

    *email* — required by Let's Encrypt in non-interactive mode.
    *expand* — if True, adds *domain* to the existing certificate
    (``certbot --nginx -d <domain> --expand``).
    """
    _validate_domain(domain)
    cmd = ["sudo", "certbot", "--nginx", "-d", domain, "--non-interactive", "--agree-tos"]
    if email:
        cmd.extend(["-m", email])
    else:
        cmd.append("--register-unsafely-without-email")
    if expand:
        cmd.append("--expand")
    try:
        subprocess.run(cmd, check=True, timeout=300)  # 5 min for DNS-01 challenges
        return True
    except subprocess.CalledProcessError as e:
        print(f"certbot failed: {e}", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("certbot not found", file=sys.stderr)
        return False
