"""Nginx configuration helper for the cache server.

Detects existing nginx state, generates reverse-proxy configuration,
and manages Let's Encrypt certificates via certbot.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

NGINX_SITES_AVAILABLE = Path("/etc/nginx/sites-available")
NGINX_SITES_ENABLED = Path("/etc/nginx/sites-enabled")
NGINX_CONFIG_NAME = "fw-cache"


def detect_nginx() -> dict:
    """Detect the current nginx state on the system.

    Returns a dict with keys:
        installed (bool), running (bool), has_https (bool), domains (list[str])
    """
    result = {"installed": False, "running": False, "has_https": False, "domains": []}

    # Check if nginx binary exists
    if shutil := _try_shutil():
        nginx_bin = shutil.which("nginx")
        if not nginx_bin:
            return result
    else:
        return result

    result["installed"] = True

    # Check if nginx is running
    try:
        subprocess.run(["systemctl", "is-active", "--quiet", "nginx"], check=True, timeout=5)
        result["running"] = True
    except Exception:
        pass

    # Detect existing HTTPS configs
    if NGINX_SITES_ENABLED.exists():
        for conf in NGINX_SITES_ENABLED.iterdir():
            if conf.is_symlink() or conf.is_file():
                try:
                    content = conf.read_text()
                    if "listen 443 ssl" in content or "listen [::]:443 ssl" in content:
                        result["has_https"] = True
                        # Extract server_name
                        for line in content.splitlines():
                            line = line.strip()
                            if line.startswith("server_name ") and ";" in line:
                                names = line.replace("server_name ", "").replace(";", "").split()
                                result["domains"].extend(names)
                except Exception:
                    pass

    return result


def _try_shutil():
    try:
        import shutil
        return shutil
    except ImportError:
        return None


def detect_certbot() -> dict:
    """Check certbot availability.

    Returns a dict with keys:
        installed (bool), has_certificates (bool)
    """
    result = {"installed": False, "has_certificates": False}
    shutil = _try_shutil()
    if not shutil:
        return result

    if shutil.which("certbot"):
        result["installed"] = True

    cert_dir = Path("/etc/letsencrypt/live")
    if cert_dir.exists() and any(cert_dir.iterdir()):
        result["has_certificates"] = True

    return result


def generate_nginx_config(domain: str, proxy_port: int = 8000) -> str:
    """Generate an nginx site configuration for reverse-proxying the cache server.

    The configuration enables HTTPS on port 443 with HTTP/1.1 keep-alive,
    sets appropriate proxy headers, and includes rate limiting at 50 req/s
    with a burst of 20.
    """
    return f"""# fw-context Cache Server — nginx reverse proxy
# Generated by fw-cache-server setup

upstream fw_cache_backend {{
    server 127.0.0.1:{proxy_port};
    keepalive 32;
}}

server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Rate limiting — 50 req/s burst 20
    limit_req_zone $binary_remote_addr zone=fw_cache:10m rate=50r/s;
    limit_req zone=fw_cache burst=20 nodelay;

    location / {{
        proxy_pass http://fw_cache_backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


def write_nginx_config(domain: str, proxy_port: int = 8000) -> Path:
    """Write the nginx config file and return its path."""
    config_path = NGINX_SITES_AVAILABLE / NGINX_CONFIG_NAME
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(generate_nginx_config(domain, proxy_port))
    return config_path


def enable_nginx_site() -> None:
    """Create a symlink from sites-available to sites-enabled."""
    src = NGINX_SITES_AVAILABLE / NGINX_CONFIG_NAME
    dst = NGINX_SITES_ENABLED / NGINX_CONFIG_NAME
    if dst.exists():
        dst.unlink()
    dst.symlink_to(src)


def test_nginx_config() -> bool:
    """Run ``nginx -t`` to validate configuration.  Returns True on success."""
    try:
        subprocess.run(["nginx", "-t"], check=True, capture_output=True, text=True, timeout=10)
        return True
    except subprocess.CalledProcessError as e:
        print("nginx config test failed:", e.stderr, file=sys.stderr)
        return False
    except FileNotFoundError:
        print("nginx not found — cannot test config", file=sys.stderr)
        return False


def reload_nginx() -> bool:
    """Reload nginx.  Returns True on success."""
    try:
        subprocess.run(["systemctl", "reload", "nginx"], check=True, timeout=10)
        return True
    except Exception:
        try:
            subprocess.run(["nginx", "-s", "reload"], check=True, timeout=10)
            return True
        except Exception:
            return False


def obtain_certificate(domain: str, expand: bool = False) -> bool:
    """Obtain or expand a Let's Encrypt certificate via certbot.

    *expand* — if True, adds *domain* to the existing certificate
    (``certbot --nginx -d <domain> --expand``).
    """
    cmd = ["certbot", "--nginx", "-d", domain, "--non-interactive", "--agree-tos"]
    if expand:
        cmd.append("--expand")
    try:
        subprocess.run(cmd, check=True, timeout=120)
        return True
    except subprocess.CalledProcessError as e:
        print(f"certbot failed: {e}", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("certbot not found", file=sys.stderr)
        return False
